### ISSUE TITLE
Feature Request: Set Custom Id's

### ISSUE THREAD

**Issue by DynamiteAndy** [ashmanix/obs-plugin-countdown#100]
Hi,

I've just updated to version 2, big fan of having more capabilities with websockets and being able to have multiple timers! Love this update!

Was wondering if it would be possible to request a feature to set a custom id on a timer? (I have specific usages for timers and would love to be able to give them custom id's or names) for readability / reusing.

Thank you 😃

**Comment by ashmanix** [comment]
Hi, this was something I did think about with the timers but left it for later. This request made me think about it again and I've implemented a change today to allow you to edit the timer ID in the settings window. Note that you can't have two ID's that are the same and the plugin should give you an error popup if you do try to save a duplicate ID...at least I hope it does 🤣

The change is on version 2.0.3 which you can download a copy of in releases: https://github.com/ashmanix/obs-plugin-countdown/releases/tag/2.0.3

**Comment by andrewcartwright1** [comment]
Thank you so much!

**Comment by DynamiteAndy** [comment]
Thank you so much :D
