### ISSUE TITLE
Can't install on linux?

### ISSUE THREAD

**Issue by sconebonevideo** [ashmanix/obs-plugin-countdown#103]
current OS Linux Mint 22 Cinnamon. version of OBS is 30.1.2 flatpak. I haven't updated OBS since April because the flatpak version created difficulties with plugins, something to do with plugins that don't go through flathub won't install.  I clicked the .deb install and noticed that it didn't install in .var/app/com.obsproject.studio/config/obs-studio/plugins (generally where i'm able to drop plugins). Curious if there is a work around or something else I should try
Thanks in advance

**Comment by ashmanix** [comment]
I'll be honest, I don't use OBS on Linux and rely on the plugin template code provided by OBS to package the Windows, MacOS and Ubuntu files.

The installer is annoying as it will install in a default location which I'm not sure where that is for Ubuntu or Linux Mint. I have an Ubuntu PC I was able to test the installer on and I found that the plugin folders were installed in the following locations:

Data Files: `/usr/share/obs/obs-plugins/obs-plugin-countdown`
Main so file: `/usr/lib/x86_64-linux-gnu/obs-plugins/obs-plugin-countdown.so`

If you can locate these files in the same locations on Linux Mint you could try moving them to where Flatpak installs the plugin files and see if that works?

**Comment by sconebonevideo** [comment]
thanks for the fast reponse! I did try doing that. I'll be honest, I wouldn't know how to drop it in there and create the proper structure so that it will work?

**Comment by ashmanix** [comment]
Ok, so I tried installing OBS using flatpak on my Ubuntu setup and checked to see how that works. What to do is copy the files over into the `~/.var/app/com.obsproject.Studio/config/obs-studio/plugins/` folder under the folder name `obs-plugin-countdown`

I had to put the files into the following structure within the `obs-plugin-countdown` folder:
```
├── bin
│   └── 64bit
│       └── obs-plugin-countdown.so
└── data
    └── locale
        ├── da-DK.ini
        ├── en-GB.ini
        ├── en-US.ini
        └── pt-BR.ini
```
The plugin then showed up, though I noticed a weird bug where no timers were shown (you had to add a timer manually the first time you run the plugin).

Give this a go and see if it works.

**Comment by sconebonevideo** [comment]
no such luck. I even updated to the latest version of OBS, still the same thing. The latest version of OBS has a compatibility issue with plugins that don't get install via flatpak, hence why i use an older version. I downgraded back to my original version and the plugin doesn't pop up

**Comment by ashmanix** [comment]
For your installation of OBS are there other existing plugins installed in the same location?

**Comment by sconebonevideo** [comment]
they are all under .var/...

**Comment by ashmanix** [comment]
I put the folder in`~/.var/app/com.obsproject.Studio/config/obs-studio/plugins`. Folder name is `obs-plugin-countdown`. Try removing the version from the name.

**Comment by sconebonevideo** [comment]
ok progress. i removed the version from the name. it showed up in docks, but nothing pops up

**Comment by sconebonevideo** [comment]
oh, restart got it!

**Comment by sconebonevideo** [comment]
thanks for the help!

**Comment by ashmanix** [comment]
Glad it works! I'll close this issue now.
