### ISSUE TITLE
No such slot CountdownDockWidget::ToggleHoursCheckBoxSelected(int)

### ISSUE THREAD

**Issue by eribertomota** [ashmanix/obs-plugin-countdown#11]
Hi @ashmanix,

When running OBS, I can see the following messages in the log:

```
info: ---------------------------------
QObject::connect: No such slot CountdownDockWidget::ToggleHoursCheckBoxSelected(int)
QObject::connect:  (sender name:   'hoursCheckBox')
QObject::connect:  (receiver name: 'CountdownTimer')
QObject::connect: No such slot CountdownDockWidget::ToggleMinutesCheckBoxSelected(int)
QObject::connect:  (sender name:   'minutesCheckBox')
QObject::connect:  (receiver name: 'CountdownTimer')
QObject::connect: No such slot CountdownDockWidget::ToggleSecondsCheckBoxSelected(int)
QObject::connect:  (sender name:   'secondsCheckBox')
QObject::connect:  (receiver name: 'CountdownTimer')
info: [ashmanix-countdown] plugin loaded successfully (version 1.1.0)
```

These messages seems a little problem in source code, so I am sending for you.

Thanks!

**Comment by ashmanix** [comment]
Hi @eribertomota I don't see these errors on my logs when running on a M1 Mac. What OS are you using?

**Comment by eribertomota** [comment]
Hi @ashmanix,

Initially, thanks for your attention for my other bugs and PRs.

I am using Debian Testing from today, and I was using Debian Stable (Linux). I can see these messages on both versions. I found something about these messages here[1].

[1] https://stackoverflow.com/questions/10656510/qt-connect-no-such-slot-when-slot-definitely-does-exist

I am able to test any patch (PR) from you.

Thanks again!

**Comment by ashmanix** [comment]
I've ran v1.1.0 of the plugin in Ubuntu (v22.04.2) using OBS v29.0.2 and I don't see this issue. I installed the plugin using the .deb file that is attached to the latest release on my repo.

Could this be to do with the package of the plugin that you sent to Debian? There might have been an issue when the plugin was compiled. According to the link you have shown it could be something to do with the compiled files. When I compile the files on my repo I am using GitHub actions that creates a clean instance of the Linux OS each time it compiles the plugin so there shouldn't be any issue with left over files not being cleaned up.

**Comment by eribertomota** [comment]
I forgot to say that I can see this issue running the obs from command line. After exiting the obs, on the screen, there are several messages and I can see what I said. Here you can see the build of 1.1.0 on amd64 on Debian[1].

[1] https://buildd.debian.org/status/fetch.php?pkg=obs-ashmanix-countdown&arch=amd64&ver=1.1.0-3&stamp=1675702641&raw=0

Currently, I maintain 10 plugins[2] and the countdown[3] is the only plugin showing these warnings.

[2] https://qa.debian.org/developer.php?email=eriberto@debian.org
[3] https://tracker.debian.org/pkg/obs-ashmanix-countdown

Thanks again!

![countdown](https://user-images.githubusercontent.com/6435502/219900965-1e1da858-172e-4f60-a014-04bc98671020.jpg)

**Comment by ashmanix** [comment]
Thanks for the screenshot. I've had a look at the code and realised that there was unused code for three SLOTs that didn't exist anymore. I have removed this code and will merge the changes into the master branch later today. Please see https://github.com/ashmanix/obs-plugin-countdown/pull/19 for the specific fix.

**Comment by ashmanix** [comment]
This fix has now been merged into the master branch.

**Comment by eribertomota** [comment]
Confirmed. Thanks.
