### ISSUE TITLE
Please, provide en-US.ini

### ISSUE THREAD

**Issue by eribertomota** [ashmanix/obs-plugin-countdown#12]
The default file for language is en-US.ini. On most computers, this file will be used. On Debian, I am providing an en-US.ini, identical to en-GB.ini.

I did little changes in en-GB.ini to try reduce the width of the dock. My first PR will be about these changes.

Thanks!

**Comment by ashmanix** [comment]
en-US file now added to the plugin on the master branch. I'm closing out this issue.
