### ISSUE TITLE
[Feature Request] Remember last configured settings

### ISSUE THREAD

**Issue by andrewcartwright1** [ashmanix/obs-plugin-countdown#18]
Hi,

This is a great plugin! Thank you for sharing this!

I was just wondering if it would be possible to add a feature to remember the last configured settings?
Even if just the source, scene and message 😃 

Thank you very much for your time and work on this plugin!

**Comment by ashmanix** [comment]
Hi @andrewcartwright1 the app should already do this. Can you tell me a couple of things about your setup:
- What OS are you using?
- What version of the plugin are you using?
- Did you install the plugin using the installer or did you manually paste the plugin files to a location?
- Do you have a copy of the logs OBS creates when you open the app? Looking through them for any errors to do with [obs-plugin-countdown] would help me understand the issue.

The plugin should be saving the following when you close OBS:
- Source selected for test display
- Message text (and whether it is ticked as an option)
- Scene selected (and whether it is ticked as an option)
- The hours, minutes, seconds set under the h/m/s tab.

**Comment by andrewcartwright1** [comment]
Sure, Thank you very much for getting back to me! Its really appreciated

-  I am using 64bit Windows 11, With the latest version of OBS available on steam (29.0.2),
- Latest version of the plugin 1.10,
- I installed it using the installer,

I deleted my logs, started afresh and opened/closed a few times after setting some settings

```
15:29:30.076: [obs-plugin-countdown] plugin loaded successfully (version 1.1.0)
15:29:30.362:     obs-plugin-countdown.dll
15:30:24.304: [obs-plugin-countdown] Hotkey ID: 3, Value: Ashmanix_Countdown_Timer_To_Time_Start
15:30:24.304: [obs-plugin-countdown] Hotkey ID: 4, Value: Ashmanix_Countdown_Timer_To_Time_Stop
```

and then when i close obs..

```
15:30:24.462: [obs-plugin-countdown] plugin unloaded
15:30:24.545:      ┃ ┣obs_init_module(obs-plugin-countdown.dll): 22.208 ms
```

The reopen logs have the exact same number of logs and events (6), just different timestamps - I have attached these

[2023-02-19 15-29-28.txt](https://github.com/ashmanix/obs-plugin-countdown/files/10777269/2023-02-19.15-29-28.txt)
[2023-02-19 15-33-48.txt](https://github.com/ashmanix/obs-plugin-countdown/files/10777270/2023-02-19.15-33-48.txt)
[2023-02-19 15-35-36.txt](https://github.com/ashmanix/obs-plugin-countdown/files/10777271/2023-02-19.15-35-36.txt)

**Comment by ashmanix** [comment]
Thanks for the heads up on this! 
I tried deleting the config folder and running OBS and I was able to replicate the same behaviour where the configuration wouldn't be saved if a folder didn't already. I've updated the code to create this folder if one isn't found.

**Comment by andrewcartwright1** [comment]
That's awesome! Thank you very much :D

**Comment by ashmanix** [comment]
Closing this out as I've created a new release (v1.2.0) with the fix and tested it locally on a Windows PC and it now seems to be working.
