### ISSUE TITLE
[Feature Request] Api to send requests to set/start/stop timer?

### ISSUE THREAD

**Issue by andrewcartwright1** [ashmanix/obs-plugin-countdown#30]
Hi

I've been messing on with touch portal and i was wondering if it's possible to set/start/stop a timer via a api?
I have some redeems that use the countdown and i currently set it manually, but wondering if it may be possible to do this with a api?

Many thanks

**Comment by ashmanix** [comment]
Hi, I have no current plan to create an API and I'm not too familiar with Touch Portal but there are a list of shortcuts available for the timer that you can set in OBS please see [here](https://github.com/ashmanix/obs-plugin-countdown/wiki#obs-hotkeys). Is it possible to set the shortcuts for these in OBS and then use Touch Portal to activate these shortcuts with a button press?

**Comment by dog199200** [comment]
So what you're saying is you have no intent to expose any of the variables "correctly" so they can be accessed by third party apps like touch portal, macro deck, or stream deck AND that streamers who use these tools, which are becoming more common, should not waste their time. 

Do the community a favor and make this open source so those of us who would actually do it can xD

**Comment by ashmanq** [comment]
Not how I would word it but as I've said I've no plan at present mainly because I don't know how to expose the variables via an API, as a plugin within OBS unless the OBS SDK allows this somehow.

Are there any other OBS plugins, that you use, that gives you this functionality? I can have a look at their source code to see what they have done and attempt this.

**Comment by ashmanix** [comment]
> So what you're saying is you have no intent to expose any of the variables "correctly" so they can be accessed by third party apps like touch portal, macro deck, or stream deck AND that streamers who use these tools, which are becoming more common, should not waste their time.
> 
> So time for me to stop being lazy, download the source code, and look into doing it myself for people since I need this done too.

Not how I would word it but as I've said I've no plan at present mainly because I don't know how to expose the variables via an API, as a plugin within OBS unless the OBS SDK allows this somehow.

Are there any other OBS plugins, that you use, that gives you this functionality? I can have a look at their source code to see what they have done and attempt this.

**Comment by andrewcartwright1** [comment]
> Hi, I have no current plan to create an API and I'm not too familiar with Touch Portal but there are a list of shortcuts available for the timer that you can set in OBS please see [here](https://github.com/ashmanix/obs-plugin-countdown/wiki#obs-hotkeys). Is it possible to set the shortcuts for these in OBS and then use Touch Portal to activate these shortcuts with a button press?

No worries! I had a look into the hotkeys this morning whilst I had time

![image](https://github.com/ashmanix/obs-plugin-countdown/assets/10059155/ee4b4862-af46-4014-8fe4-8d4c38bbf817)

Sadly this wouldn't do what I need it to do, I use a variety of different periods, and scenes - so I'd need to be able to change these on the fly.

> Are there any other OBS plugins, that you use, that gives you this functionality? I can have a look at their source code to see what they have done and attempt this.

It looks like AdvancedSceneSwitcher has just added something similar to this using websockets: https://github.com/WarmUpTill/SceneSwitcher/wiki/Switching-scenes-for-Aitum-Vertical-plugin - Thoughts are, the countdown could listen to certain websocket events?

https://github.com/obsproject/obs-websocket Not sure if this is food for thought?

I appreciate you getting back to me on this!

**Comment by ashmanix** [comment]
The same functions actionable with hotkeys are now actionable using a websocket connection in version 1.3.2. Refer to the wiki [here](obs_websocket_vendor_unregister_request) for details.

**Comment by andrewcartwright1** [comment]
Got this hooked up to my touchportal and it is working beautifully! Cant wait to see what other features get added to extend websockets :D

**Comment by ashmanix** [comment]
Awesome! Glad to hear it works.
