### ISSUE TITLE
Ability to set multiple countdowns at the same time

### ISSUE THREAD

**Issue by Destroy666x** [ashmanix/obs-plugin-countdown#32]
Would be nice if you could set up multiple countdowns at the same time. 

How I imagine it:
- tabbed interface at the top of dock, tabs have `x` buttons on the right to end timers, otherwise clicking on a tab switches to it
- `+` button to the right of last tab to add another tab
- if new tab would overflow current width of widget, start a new line, maybe with some maximum of lines
- each countdown simply implements the same mechanics as current single countdown

**Comment by ashmanix** [comment]
I don't have any plans to do this in the near future, so closing this ticket.
