### ISSUE TITLE
Fallback to old value once source is not a countdown anymore

### ISSUE THREAD

**Issue by Destroy666x** [ashmanix/obs-plugin-countdown#33]
It would be nice if the plugin remembered the previous value before writing its own, then if you deselect a source, it could bring back its old value.

Why?
- better integration with multi-task text sources (such as news ticker) controlled also by other plugins
- less prone to user fails and e.g. accidentally overwriting long text value in a source selected by mistake

**Comment by ashmanix** [comment]
Thanks for the suggestion. No plans at this stage to implement so closing for now but will look into this if more people ask for it.
