### ISSUE TITLE
cant use Pango Text as source

### ISSUE THREAD

**Issue by oparada1988** [ashmanix/obs-plugin-countdown#34]
On linux the default test source doesnt have a lot of customization like changing the outline color, thicknes etc so I use the pango plug in, https://github.com/kkartaltepe/obs-text-pango

However, the countdown plugin doesnt see it as a source. Would be cool if it could see it as pango is much more customizable than the default option.

**Comment by ashmanix** [comment]
I have added `text_pango_source` to the list of sources that will appear as an source to select. I have tested this in Ubuntu, with the pango text plugin, and it seems to work covered by PR #40. This is available in [version 1.3.3](https://github.com/ashmanix/obs-plugin-countdown/releases/tag/1.3.3)

**Comment by oparada1988** [comment]
Thank you! I will test on my machine and report back in the AM

**Comment by oparada1988** [comment]
Just wanted to confirm that it works as expected! Thanks again!

**Comment by ashmanix** [comment]
Awesome! Closing this now 👍
