### ISSUE TITLE
[Feature Request] Auto start timer when scene with text source becomes active

### ISSUE THREAD

**Issue by DaBenjamins** [ashmanix/obs-plugin-countdown#37]
I would like to see the option to have a Auto Start Timer, where it will auto start (reset if using period mode) when the scene that contains the text source become active. This would allow for a precise "5 min" wait screen

**Comment by ashmanix** [comment]
I have no plans to implement this just now but you could try using websocket commands to send a command to the plugin to start the timer. I believe there might be an automation plugin that allows you do try this out (though I might be wrong). The plugin hooks into the websocket and can take commands to stop/start the timer for period or datetime. Documentation on this is available here:
https://github.com/ashmanix/obs-plugin-countdown/wiki#websocket-hooks

**Comment by Destroy666x** [comment]
@DaBenjamins this is doable with Advanced Scene Switcher + WebSockets. Condition - scene active or source visisble or whatever. Action - send WS message to this plugin to start timer.
