### ISSUE TITLE
[Feature Request] Day countdown in timer

### ISSUE THREAD

**Issue by lethargicwaldo** [ashmanix/obs-plugin-countdown#45]
Hello,

Thank you for making this awesome plugin, I was curious if a feature that included number of days until the timer hits zero would be possible to add? I work for an educational establishment and have been making use of this to countdown to events, and want to put a timer up 4-5 days in advance and display those days.

Thanks again!

**Comment by ashmanix** [comment]
Have a look at the latest version of the plugin I've just released (version 1.4.1): https://github.com/ashmanix/obs-plugin-countdown/releases/tag/1.4.1

I've added in a feature to include days in the countdown. Closing this issue now.
