### ISSUE TITLE
Problem installing on debian

### ISSUE THREAD

**Issue by jpazsedano** [ashmanix/obs-plugin-countdown#47]
I installed the plugin on debian and it just doesn't get loaded. I found out this in the obs logs:

```
error: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/obs-plugin-countdown.so->/usr//lib/x86_64-linux-gnu/obs-plugins/obs-plugin-countdown.so): libQt6Widgets.so.6: Failed to open file or shared object: No such file or directory
```

The file does exists, and has read permissions for everyone. So I guess the error is in the double slash ('/usr//lib/x86...'). But I have no idea why it was installed like that or what config file is obs getting that path from, if that's on the installation package or where is it. All I've done is dpkg-ing the *.deb file and OBS is a clean install I just added right before installing the plugin on a computer that never before had OBS installed. If i would been messing around with OBS before installing the plugin I would think that the problem is in my installation and not the plugin, because it really looks like a system problem, but I haven't been messing around. That's why I'm confused and I open this.

I'm using OBS 29.0.2 on Debian 12. Ask me if you need more info.

**Comment by eribertomota** [comment]
OBS on Debian 12 uses Qt5, so any plugin using Qt6 will fail.

**Comment by eribertomota** [comment]
This plugin is already packaged on Debian. `apt install obs-ashmanix-countdown`
