### ISSUE TITLE
Suggestion: Time to Text File

### ISSUE THREAD

**Issue by dog199200** [ashmanix/obs-plugin-countdown#48]
It would be nice if we could save the time into a text file so it can be read from in other elements. This can be helpful if OBS crashes or the OBS instance is closed, it would allow the timer to remember it's previous time. This is great is someone wanted to use the timer for a subathon or something.

**Comment by ashmanix** [comment]
Thanks for the suggestion, I have no plans at this point to implement something like this but will look at it in the future if enough people ask for it.

Closing issue for now.
