### ISSUE TITLE
Suggestion: OBS Hotkey Support

### ISSUE THREAD

**Issue by WaldoAndFriends** [ashmanix/obs-plugin-countdown#5]
First of all great work!
The plugin is really easy to use. However, I do miss a feature that could make it even better:
**Hotkey support**

This way I could for example automate the `start`, `pause` and `reset` of the countdown using stream automation software like Streamer.Bot or SAMMI. Enabling users to automatically start the timer when the stream starts for instance, or any other usage people might come up with.

**Comment by ashmanix** [comment]
Awesome suggestion! I've implemented this in the code but I plan to try and implement one new feature before I do another release incorporating the new changes.

**Comment by ashmanix** [comment]
New release now available with hotkeys: [Release 1.1.0](https://github.com/ashmanix/obs-plugin-countdown/releases/tag/1.1.0)

**Comment by WaldoAndFriends** [comment]
Thanks for including it! 👍🏻
