### ISSUE TITLE
different countdowns by scene group

### ISSUE THREAD

**Issue by myrrien** [ashmanix/obs-plugin-countdown#52]
if I set a countdown in a scene group then change scene group and set another one, the prevoius one is overwritten.

**Comment by ashmanix** [comment]
This is how the plugin is meant to work currently. It is designed to only handle one specific text source with one counter. 

Are you wanting to have more than one timer where each one is in a different scene?

**Comment by myrrien** [comment]
Yes, I stream for different twitch channels, each one has it's own scene group, and I'd like each one to have its own timer

**Comment by ashmanix** [comment]
I have no plans at this point to add multiple timers mainly because it would require a big rewrite of my (bad code) to take on multiple instances and the UI changes would be tricky.

Closing this for now but might look at some point in the future.
