### ISSUE TITLE
Feature Request: Add time through websocket or similar

### ISSUE THREAD

**Issue by ViP3R76** [ashmanix/obs-plugin-countdown#53]
Request:
Add xx:xx:xx to the actually set or running counter.

For example: Timer is already running at 00:04:30 and i want to add 1min/30sec it should continue with 00:06:00.

Through websocket: 
- add 5m will be automatically translated to 00:05:00 as addition
- add 30s will be automatically adding 00:00:30
- add 1h will be automatically adding 01:00:00
- add 00:10 will be automatically adding 10 minutes
- add 01:00 will be automatically adding 1 hour
- ...

**Comment by JzTurrini** [comment]
Yeah, same for me, but I'd suggest something way easier, like:

00:01:00 to change the timer to 1 minute.
01:00:00 to change the timer to 1 hour.

Because I use this plugin in my live stream and I have different situations with different timers, and I always have to set it manually.
