### ISSUE TITLE
request - please create a tutorial to create a custom dock in obs :( 

### ISSUE THREAD

**Issue by nirvanaruns** [ashmanix/obs-plugin-countdown#56]
Hello, I wanted to know if you could make a new video tutorial on generating things for OBS.
My intention is to learn how to make an OBS dock which allows me to make changes to text files on my computer located in the X directory, use labels, etc. The idea of ​​the project is to create a score bar which will be used in fighting game tournament streams. I have external alternatives to do this but I would like to implement it as an OBS dock so I can manage everything from there.

Aside from that, I followed your video tutorial (https://www.youtube.com/watch?v=n1F8iPAbbHg) but I couldn't even compile the default template plugin. I have computer science studies but I never learned c++ and to be honest I was not very good at programming but I do make an effort to do it when the project motivates me (that is, this case)...

Will it be possible for you to help me with that? create a mini tutorial perhaps on how to create a custom dock in OBS, that has perhaps 1 button and compile it so that it works well?

Thank you very much in advance friend :)

**Comment by foocode** [comment]
Hi @nirvanaruns , it's not too hard to adapt the tutorial vid on youtube. Check out replacing the deprecated call with the new replacement call: https://docs.obsproject.com/reference-frontend-api#c.obs_frontend_add_dock_by_id

**Comment by ashmanix** [comment]
@nirvanaruns were you able to get the template to run eventually? I noticed there were issues at one point with the template compiling due to one of it's external dependencies which I think might be fixed now.

**Comment by ashmanix** [comment]
Closing this due to no reply in a while.
