### ISSUE TITLE
Time format mm:ss under 2 digit time set

### ISSUE THREAD

**Issue by Pepealcrack** [ashmanix/obs-plugin-countdown#58]
ES:
Me preguntaba, ¿como puedo mostrar el tiempo con el 0 delante de una cifra de un solo dígito? Me explico, cuando el tiempo cambia de 10:00 a 9:59 quiero que se siga viendo en formato mm:ss o sea que se vea 09:59.

EN (google translation):
I was wondering, how can I display the time with the 0 in front of a single digit number? Let me explain, when the time changes from 10:00 to 9:59 I want it to continue being displayed in mm:ss format, meaning that it will be displayed at 09:59.

**Comment by JzTurrini** [comment]
It will show if you decide to also show the hour, if you choose to display only minutes and seconds it will put as 9:59 instead of 00:09:59. Don't know why it is like this.

**Comment by ashmanix** [comment]
I've now added a featuer where you can set whether you want a leading zero or not in version 1.4.1: 
https://github.com/ashmanix/obs-plugin-countdown/releases/tag/1.4.1
