### ISSUE TITLE
Change Timer

### ISSUE THREAD

**Issue by JzTurrini** [ashmanix/obs-plugin-countdown#75]
I was checking the wiki, and now we have a way to control the plugin via websocket; this is great.
But I want to know if is possible to change the set timer. For example:

- The timer is set to 2 minutes
- I want to set it to 5 minutes before I put to run it again

Is it possible to do it via websocket? I saw only an option to add time.

**Comment by ashmanix** [comment]
I haven't implemented this functionality but it was something I was thinking needs to be done. I'm going to see if I can get it implemented in the next few days while I have some time. I'll try and get it ready for the next release which will include the add time feature that's on the wiki (currently this is in the code but not in a release yet).
