### ISSUE TITLE
obs-plugin-countdown was sent to Debian (Linux)

### ISSUE THREAD

**Issue by eribertomota** [ashmanix/obs-plugin-countdown#8]
Hi @ashmanix,

Initially, thanks a lot for your work.

Today I packaged and I sent this plugin to Debian. I think it will be accepted up tomorrow (but is very common for a new package to wait up to 3 months). If you want to see the packaging, please, check this link[1].

[1] https://salsa.debian.org/eriberto/obs-ashmanix-countdown/-/tree/debian/master/debian

From now, I will send some patches and open issue(s) to try to help you with some changes and fixes.

I sent the plugin using the name obs-ashmanix-countdown, because this is the name used here[2] and because obs-plugin-countdown, IMHO, seem very generic.

[2] https://obsproject.com/forum/resources/ashmanix-countdown-timer.1610/

To change the name, I handled in CMakeLists.txt:

-project(obs-plugin-countdown VERSION 1.1.0)
+project(ashmanix-countdown VERSION 1.1.0)

I removed 'obs-' because this prefix is used by plugins distributed with OBS, but the package name is obs-ashmanix-countdown (but the lib is ashmanix-countdown only).

I would like to take the opportunity to leave the idea of doing a dock count up to guide youtubers as to the elapsed time.

Regards,

Eriberto

**Comment by eribertomota** [comment]
I forgot to say that your plugin is set as 64bit here[1], but it worked fine over 32bit too.

[1] https://obsproject.com/forum/resources/ashmanix-countdown-timer.1610/

I also would like to suggest to update the copyright notice in the files `src/plugin-main.cpp` and s`rc/plugin-macros.h.in`. See the current status:

```
src/plugin-macros.h.in:Copyright (C) 2022 @PLUGIN_AUTHOR@ @LINUX_MAINTAINER_EMAIL@
src/plugin-main.cpp:Copyright (C) <Year> <Developer> <Email Address>
```

This is very important for all packagers on all systems.

**Comment by ashmanix** [comment]
Hi @eribertomota, thanks for informing me. I'll keep your suggestions in mind going forward. I will have a look at the issues and PR's you have made and review them. I will close this comment off now.

Thanks
