### ISSUE TITLE
Count down from time depends of the h/m/s

### ISSUE THREAD

**Issue by eribertomota** [ashmanix/obs-plugin-countdown#9]
Hi @ashmanix,

I can't make the `time mode` to work without set at least 1 second on `h/m/s` on my machine. I think this is a bug.

Regards,

Eriberto

**Comment by ashmanix** [comment]
Hi @eribertomota I've purposely made it so that you need to at least set 1 second to set the timer. I'm going to close this issue for now. Thanks!

**Comment by eribertomota** [comment]
What you think about to display an error to final user to make this procedure more intuitive?
